package presentation;
import application.AuditResult;
public class ReportGeneration {
    public String generate(AuditResult result,
            String patientName, String ssn, String ailment, String medication,
            int dosage, String doctorName, String specialization, String username) {
        StringBuilder sb = new StringBuilder();
        sb.append("--- CLINICAL AUDIT REPORT ---\n");
        sb.append("Timestamp: ").append(java.time.LocalDateTime.now()).append("\n\n");
        sb.append("Patient Name: ").append(patientName).append("\n");
        sb.append("SSN: ").append(ssn).append("\n");
        sb.append("Ailment: ").append(ailment).append("\n\n");
        sb.append("Medication: ").append(medication).append("\n");
        sb.append("Dosage: ").append(dosage).append(" mg\n\n");
        sb.append("Doctor: ").append(doctorName).append("\n");
        sb.append("Specialization: ").append(specialization).append("\n\n");
        sb.append("--- Audit Findings ---\n");
        for (String msg : result.getMessages()) {
            sb.append("> ").append(msg).append("\n");
        }
        sb.append("\nFinal Compliance Score: ")
          .append(result.getCompliance()).append("%\n");
        sb.append("\nGenerated By: ").append(username).append("\n");
        return sb.toString();
    }
}